import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
  },
  header: {
    paddingHorizontal: 26,
    paddingTop: 18,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  iconButton: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    color: '#ffffff',
    fontSize: 28,
    fontWeight: '800',
    letterSpacing: -0.8,
  },
  content: {
    paddingBottom: 160,
  },
  heroArea: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 18,
    paddingBottom: 38,
  },
  heroGlow: {
    position: 'absolute',
    width: 330,
    height: 330,
    borderRadius: 165,
    backgroundColor: 'rgba(255,255,255,0.18)',
    opacity: 0.55,
  },
  heroImage: {
    width: 340,
    height: 340,
    resizeMode: 'contain',
  },
  heroMeta: {
    position: 'absolute',
    bottom: 10,
    alignItems: 'center',
    gap: 10,
  },
  heroId: {
    color: 'rgba(255,255,255,0.84)',
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: 2,
  },
  heroTypeRow: {
    flexDirection: 'row',
    gap: 8,
  },
  heroTypePill: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.18)',
  },
  heroTypeText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
  },
  sheet: {
    minHeight: 408,
    paddingHorizontal: 28,
    paddingTop: 10,
    paddingBottom: 138,
    backgroundColor: '#1c1c1c',
    borderTopLeftRadius: 42,
    borderTopRightRadius: 42,
  },
  sheetHandle: {
    alignSelf: 'center',
    width: 58,
    height: 4,
    borderRadius: 999,
    backgroundColor: '#5b5b5b',
    marginBottom: 22,
  },
  tabsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 24,
  },
  tabButton: {
    alignItems: 'center',
    gap: 7,
  },
  tabText: {
    color: '#7c7c7c',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  activeTabText: {
    color: '#ffffff',
  },
  activeTabDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#ffffff',
  },
  sectionBody: {
    gap: 14,
  },
  sectionIntro: {
    color: '#b2b2b2',
    fontSize: 15,
    lineHeight: 22,
  },
  typeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  typeChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  typeChipText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
  },
  infoCard: {
    borderRadius: 22,
    padding: 18,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.04)',
    gap: 8,
  },
  infoCardTitle: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
  },
  infoCardText: {
    color: '#bcbcbc',
    fontSize: 15,
    lineHeight: 23,
  },
  infoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 12,
  },
  infoCell: {
    width: '47%',
    borderRadius: 22,
    padding: 16,
    backgroundColor: 'rgba(255,255,255,0.05)',
    gap: 6,
  },
  infoCellLabel: {
    color: '#8f8f8f',
    fontSize: 13,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  infoCellValue: {
    color: '#ffffff',
    fontSize: 17,
    fontWeight: '700',
  },
  statsList: {
    gap: 18,
  },
  statRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  statLabel: {
    width: 82,
    color: '#909090',
    fontSize: 16,
  },
  statValue: {
    width: 34,
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
  },
  statTrack: {
    flex: 1,
    height: 6,
    borderRadius: 999,
    backgroundColor: '#373737',
    overflow: 'hidden',
  },
  statFill: {
    height: '100%',
    borderRadius: 999,
  },
  moveCard: {
    borderRadius: 24,
    padding: 18,
    backgroundColor: 'rgba(255,255,255,0.05)',
    gap: 14,
  },
  moveHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  moveName: {
    color: '#ffffff',
    fontSize: 17,
    fontWeight: '700',
    flex: 1,
  },
  moveMetaPill: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  moveMetaPillText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '700',
  },
  moveMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  moveMetaItem: {
    minWidth: '47%',
    gap: 4,
  },
  moveMetaLabel: {
    color: '#8f8f8f',
    fontSize: 12,
    textTransform: 'uppercase',
    letterSpacing: 0.7,
  },
  moveMetaValue: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '700',
  },
  evolutionList: {
    gap: 12,
  },
  evolutionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    borderRadius: 24,
    padding: 14,
    backgroundColor: 'rgba(255,255,255,0.05)',
  },
  evolutionImage: {
    width: 82,
    height: 82,
    resizeMode: 'contain',
  },
  evolutionName: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '700',
    flex: 1,
  },
  loadingWrap: {
    paddingHorizontal: 28,
    paddingTop: 40,
    paddingBottom: 180,
    alignItems: 'center',
    gap: 14,
  },
  loadingText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
  loadingSubtext: {
    color: '#d9d9d9',
    fontSize: 14,
    textAlign: 'center',
  },
  errorCard: {
    marginHorizontal: 28,
    marginTop: 40,
    borderRadius: 28,
    padding: 24,
    backgroundColor: 'rgba(28, 28, 28, 0.9)',
    gap: 12,
  },
  errorTitle: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: '800',
  },
  errorText: {
    color: '#d0d0d0',
    fontSize: 15,
    lineHeight: 22,
  },
  retryButton: {
    alignSelf: 'flex-start',
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.12)',
  },
  retryButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
  },
  petal: {
    position: 'absolute',
    width: 12,
    height: 28,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.78)',
  },
  petalLarge: {
    position: 'absolute',
    width: 22,
    height: 48,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.82)',
  },
});
