import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#070707' },
  content: { paddingHorizontal: 20, paddingTop: 18, paddingBottom: 100, gap: 18 },
  headerStack: { gap: 18 },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  iconButton: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
  title: { color: '#fff', fontSize: 27, fontWeight: '900' },
  subtitle: { color: '#aaa', fontSize: 14, lineHeight: 21 },
  composer: { padding: 17, borderRadius: 25, backgroundColor: '#151515', gap: 11, borderWidth: 1, borderColor: '#292929' },
  sectionTitle: { color: '#fff', fontSize: 17, fontWeight: '900' },
  input: { minHeight: 47, paddingHorizontal: 14, borderRadius: 16, color: '#fff', backgroundColor: '#090909', borderWidth: 1, borderColor: '#292929' },
  row: { flexDirection: 'row', gap: 9 },
  flex: { flex: 1 },
  oddsInput: { width: 120 },
  primaryButton: { minHeight: 47, paddingHorizontal: 14, alignItems: 'center', justifyContent: 'center', borderRadius: 17, backgroundColor: '#f8df94' },
  primaryButtonText: { color: '#111', fontWeight: '900', fontSize: 14 },
  secondaryButton: { minHeight: 45, paddingHorizontal: 13, alignItems: 'center', justifyContent: 'center', borderRadius: 16, backgroundColor: '#292929' },
  secondaryButtonText: { color: '#eee', fontWeight: '800', fontSize: 13, textAlign: 'center' },
  disabledButton: { opacity: 0.35 },
  selectedPokemon: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 8, borderRadius: 17, backgroundColor: '#0b0b0b' },
  selectedImage: { width: 54, height: 54 },
  selectedName: { color: '#fff', fontSize: 17, fontWeight: '800' },
  meta: { color: '#929292', fontSize: 12, lineHeight: 18 },
  searchResult: { flexDirection: 'row', alignItems: 'center', gap: 10, padding: 8, borderRadius: 15, backgroundColor: '#0b0b0b' },
  resultImage: { width: 38, height: 38 },
  resultText: { flex: 1, color: '#eee', fontSize: 14, fontWeight: '700' },
  huntCard: { padding: 18, borderRadius: 27, backgroundColor: '#151515', borderWidth: 1, borderColor: '#292929', gap: 12 },
  foundCard: { borderColor: 'rgba(248,223,148,0.55)' },
  huntTop: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  huntImage: { width: 64, height: 64 },
  huntName: { color: '#fff', fontSize: 21, fontWeight: '900' },
  attempts: { color: '#fff', fontSize: 42, fontWeight: '900', textAlign: 'center', marginTop: 2 },
  attemptLabel: { color: '#999', fontSize: 13, textAlign: 'center', marginTop: -10 },
  counterRow: { flexDirection: 'row', gap: 7 },
  counterButton: { flex: 1, minHeight: 48, borderRadius: 15, alignItems: 'center', justifyContent: 'center', backgroundColor: '#292929' },
  counterPrimary: { backgroundColor: '#fff' },
  counterText: { color: '#ddd', fontSize: 15, fontWeight: '900' },
  counterPrimaryText: { color: '#111' },
  probabilityCard: { padding: 14, borderRadius: 18, backgroundColor: 'rgba(248,223,148,0.08)', gap: 5 },
  probabilityTitle: { color: '#f8df94', fontSize: 13, fontWeight: '900' },
  probabilityText: { color: '#eee', fontSize: 13, lineHeight: 19 },
  disclaimer: { color: '#999', fontSize: 11, lineHeight: 17 },
  foundText: { color: '#f8df94', fontSize: 14, fontWeight: '800', textAlign: 'center' },
  foundForm: { gap: 9 },
  formLabel: { color: '#fff', fontSize: 13, fontWeight: '800' },
  formHint: { color: '#aaa', fontSize: 11, lineHeight: 16 },
  originRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  originChip: { borderRadius: 999, paddingHorizontal: 10, paddingVertical: 8, backgroundColor: '#333' },
  originChipActive: { backgroundColor: '#f8df94' },
  originText: { color: '#ddd', fontSize: 12, fontWeight: '700' },
  originTextActive: { color: '#111' },
  segmentCount: { color: '#777', fontSize: 11, textAlign: 'center' },
  empty: { padding: 23, borderRadius: 24, backgroundColor: '#151515' },
  emptyText: { color: '#aaa', fontSize: 14, lineHeight: 21 },
});
