import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#050505',
  },
  scrollContent: {
    paddingHorizontal: 28,
    paddingTop: 18,
    paddingBottom: 186,
    gap: 24,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  iconButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: 'rgba(255,255,255,0.06)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    color: '#ffffff',
    fontSize: 42,
    fontWeight: '800',
    letterSpacing: -1.3,
  },
  subtitle: {
    color: '#b6b6b6',
    fontSize: 18,
    lineHeight: 30,
    marginTop: 10,
  },
  heroCard: {
    borderRadius: 34,
    padding: 22,
    overflow: 'hidden',
    minHeight: 640,
  },
  heroContent: {
    flex: 1,
    minHeight: 596,
    justifyContent: 'space-between',
  },
  heroGlow: {
    position: 'absolute',
    width: 250,
    height: 250,
    borderRadius: 125,
    backgroundColor: 'rgba(255,255,255,0.18)',
    right: -72,
    top: -34,
  },
  heroEyebrow: {
    color: 'rgba(255,255,255,0.72)',
    fontSize: 14,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 2.6,
  },
  heroTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 16,
  },
  heroCopyColumn: {
    flex: 1,
    gap: 12,
    minHeight: 248,
  },
  heroTitleBlock: {
    gap: 12,
  },
  heroTitle: {
    color: '#ffffff',
    fontSize: 36,
    fontWeight: '800',
    letterSpacing: -1.2,
    lineHeight: 40,
  },
  heroBadge: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: 'rgba(0,0,0,0.18)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    maxWidth: '100%',
  },
  heroBadgeText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
  },
  heroPreviewCard: {
    width: 118,
    borderRadius: 24,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
    backgroundColor: 'rgba(0,0,0,0.14)',
  },
  heroPreviewImage: {
    width: '100%',
    aspectRatio: 0.9,
    justifyContent: 'flex-end',
  },
  heroPreviewImageInner: {
    resizeMode: 'cover',
  },
  heroPreviewShade: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.22)',
  },
  heroPreviewCaption: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: 'rgba(0,0,0,0.38)',
  },
  heroPreviewCaptionText: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  heroMeta: {
    color: 'rgba(255,255,255,0.92)',
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 22,
    minHeight: 88,
  },
  heroLegendRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    minHeight: 42,
    alignItems: 'flex-start',
  },
  legendChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: 'rgba(0,0,0,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  legendDot: {
    width: 9,
    height: 9,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(17,17,17,0.55)',
  },
  legendChipText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
  },
  heroSummaryRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    minHeight: 114,
    alignContent: 'flex-start',
  },
  summaryPill: {
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 11,
    backgroundColor: 'rgba(0,0,0,0.16)',
  },
  summaryPillText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
  },
  heroActionRow: {
    gap: 12,
    minHeight: 124,
    justifyContent: 'flex-end',
  },
  heroButtonPrimary: {
    minHeight: 54,
    borderRadius: 24,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.18)',
  },
  heroButtonSecondary: {
    alignSelf: 'flex-start',
    minHeight: 54,
    borderRadius: 24,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.18)',
  },
  heroButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '800',
  },
  sectionTitle: {
    color: '#ffffff',
    fontSize: 28,
    fontWeight: '800',
    letterSpacing: -0.8,
    marginBottom: 14,
  },
  chipRow: {
    paddingRight: 18,
    gap: 12,
  },
  regionChip: {
    minHeight: 48,
    borderRadius: 24,
    paddingHorizontal: 18,
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  regionChipActive: {
    backgroundColor: 'rgba(255,255,255,0.14)',
    borderColor: 'rgba(255,255,255,0.18)',
  },
  regionChipText: {
    color: '#c5c5c5',
    fontSize: 15,
    fontWeight: '700',
  },
  regionChipTextActive: {
    color: '#ffffff',
  },
  mapCard: {
    borderRadius: 30,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    backgroundColor: 'rgba(255,255,255,0.03)',
  },
  mapCanvas: {
    width: '100%',
    position: 'relative',
    backgroundColor: '#141414',
  },
  mapImage: {
    resizeMode: 'cover',
  },
  mapShade: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.16)',
  },
  markerWrap: {
    position: 'absolute',
    alignItems: 'center',
    transform: [{ translateX: -9 }, { translateY: -9 }],
  },
  markerDot: {
    width: 11,
    height: 11,
    borderRadius: 6,
    backgroundColor: '#ffffff',
    borderWidth: 2,
    borderColor: '#121212',
  },
  markerDotVillage: {
    backgroundColor: '#ffe49a',
  },
  markerDotLandmark: {
    backgroundColor: '#8de8ff',
  },
  markerLabel: {
    marginTop: 6,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: 'rgba(8,8,8,0.72)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    maxWidth: 118,
  },
  markerLabelText: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '700',
    textAlign: 'center',
  },
  mapFooter: {
    paddingHorizontal: 18,
    paddingVertical: 16,
    gap: 10,
  },
  mapVariantText: {
    color: '#ffffff',
    fontSize: 17,
    fontWeight: '800',
  },
  mapSourceText: {
    color: '#8f8f8f',
    fontSize: 13,
    lineHeight: 20,
  },
  mapSourceButton: {
    alignSelf: 'flex-start',
    minHeight: 42,
    borderRadius: 21,
    paddingHorizontal: 16,
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  mapSourceButtonText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
  },
  placeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  placeCard: {
    borderRadius: 24,
    padding: 18,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  placeCardCity: {
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  placeCardVillage: {
    backgroundColor: 'rgba(255,228,154,0.12)',
  },
  placeCardLandmark: {
    backgroundColor: 'rgba(141,232,255,0.12)',
  },
  placeCardTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  placeCardTitle: {
    color: '#ffffff',
    fontSize: 17,
    fontWeight: '800',
  },
  placeCardMeta: {
    color: 'rgba(255,255,255,0.72)',
    fontSize: 13,
    marginTop: 4,
  },
  placeKindBadge: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
    backgroundColor: 'rgba(0,0,0,0.2)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  placeKindBadgeText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '700',
  },
  placePill: {
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 11,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  placePillCity: {
    backgroundColor: 'rgba(255,255,255,0.07)',
  },
  placePillVillage: {
    backgroundColor: 'rgba(255,228,154,0.12)',
  },
  placePillLandmark: {
    backgroundColor: 'rgba(141,232,255,0.12)',
  },
  placePillText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
  },
  infoCard: {
    borderRadius: 28,
    padding: 24,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    gap: 12,
  },
  infoTitle: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: '800',
  },
  infoText: {
    color: '#b8b8b8',
    fontSize: 17,
    lineHeight: 28,
  },
  backdropStripe: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: 56,
    backgroundColor: 'rgba(255,255,255,0.035)',
  },
});
