import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#070707' },
  content: { paddingHorizontal: 22, paddingTop: 18, paddingBottom: 90, gap: 18 },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  iconButton: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
  title: { color: '#fff', fontSize: 31, fontWeight: '900' },
  subtitle: { color: '#999', fontSize: 15, lineHeight: 22 },
  composer: { borderRadius: 24, padding: 16, gap: 12, backgroundColor: '#151515' },
  input: { minHeight: 48, borderRadius: 17, paddingHorizontal: 14, color: '#fff', backgroundColor: '#090909' },
  button: { minHeight: 46, borderRadius: 18, paddingHorizontal: 15, alignItems: 'center', justifyContent: 'center', backgroundColor: '#fff' },
  buttonText: { color: '#111', fontSize: 14, fontWeight: '800' },
  conflictCard: { borderRadius: 20, padding: 15, gap: 6, backgroundColor: 'rgba(248,223,148,0.09)', borderWidth: 1, borderColor: 'rgba(248,223,148,0.2)' },
  conflictTitle: { color: '#f8df94', fontSize: 14, fontWeight: '800' },
  conflictText: { color: '#d3c8aa', fontSize: 13, lineHeight: 19 },
  goalCard: { borderRadius: 26, padding: 18, gap: 14, backgroundColor: '#151515', borderWidth: 1, borderColor: '#252525' },
  goalTop: { flexDirection: 'row', justifyContent: 'space-between', gap: 12 },
  goalCopy: { flex: 1 },
  goalTitle: { color: '#fff', fontSize: 20, fontWeight: '900' },
  goalMeta: { color: '#999', fontSize: 13, marginTop: 4 },
  removeText: { color: '#ff9f9f', fontSize: 12, fontWeight: '800' },
  progressTrack: { height: 8, borderRadius: 99, backgroundColor: '#303030', overflow: 'hidden' },
  progressFill: { height: '100%', borderRadius: 99, backgroundColor: '#73d178' },
  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: { borderRadius: 99, paddingHorizontal: 10, paddingVertical: 7, backgroundColor: '#252525' },
  chipActive: { backgroundColor: '#f8df94' },
  chipText: { color: '#bbb', fontSize: 11, fontWeight: '700' },
  chipTextActive: { color: '#111' },
  task: { flexDirection: 'row', alignItems: 'flex-start', gap: 10, paddingVertical: 7 },
  checkbox: { width: 24, height: 24, borderRadius: 8, borderWidth: 1, borderColor: '#666', alignItems: 'center', justifyContent: 'center' },
  checkboxDone: { backgroundColor: '#73d178', borderColor: '#73d178' },
  taskCopy: { flex: 1 },
  taskText: { color: '#eee', fontSize: 14, lineHeight: 20 },
  taskTextDone: { color: '#777', textDecorationLine: 'line-through' },
  taskMeta: { color: '#888', fontSize: 11, marginTop: 3 },
  taskComposer: { gap: 9, paddingTop: 6 },
  twoColumns: { flexDirection: 'row', gap: 9 },
  flexInput: { flex: 1 },
  empty: { borderRadius: 24, padding: 22, backgroundColor: '#151515' },
  emptyText: { color: '#aaa', fontSize: 15, lineHeight: 22 },
});
