import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#080808' },
  content: { paddingHorizontal: 20, paddingTop: 18, paddingBottom: 90, gap: 12 },
  headerStack: { gap: 16, marginBottom: 10 },
  header: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  iconButton: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
  title: { color: '#fff', fontSize: 26, fontWeight: '900', flex: 1 },
  subtitle: { color: '#aaa', fontSize: 14, lineHeight: 21 },
  summary: { padding: 14, borderRadius: 17, backgroundColor: '#202020' },
  summaryText: { color: '#f8df94', fontSize: 14, fontWeight: '800' },
  sectionTitle: { color: '#fff', fontSize: 17, fontWeight: '900' },
  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: { borderRadius: 99, paddingHorizontal: 11, paddingVertical: 8, backgroundColor: '#292929' },
  chipActive: { backgroundColor: '#f8df94' },
  chipText: { color: '#ddd', fontSize: 12, fontWeight: '800' },
  chipTextActive: { color: '#111' },
  input: { minHeight: 45, borderRadius: 14, paddingHorizontal: 12, backgroundColor: '#181818', color: '#fff' },
  count: { color: '#aaa', fontSize: 12 },
  importCard: { padding: 15, borderRadius: 20, gap: 12, backgroundColor: '#171717' },
  hint: { color: '#aaa', fontSize: 12, lineHeight: 18 },
  importInput: { minHeight: 110, borderRadius: 14, padding: 12, backgroundColor: '#090909', color: '#fff', textAlignVertical: 'top' },
  secondaryButton: { minHeight: 42, borderRadius: 13, paddingHorizontal: 13, justifyContent: 'center', backgroundColor: '#333' },
  secondaryText: { color: '#fff', fontSize: 13, fontWeight: '800' },
  primaryButton: { minHeight: 44, borderRadius: 13, paddingHorizontal: 13, alignItems: 'center', justifyContent: 'center', backgroundColor: '#f8df94' },
  primaryText: { color: '#111', fontSize: 13, fontWeight: '900' },
  preview: { gap: 10, padding: 12, borderRadius: 15, backgroundColor: '#242424' },
  error: { color: '#ffb1b1', fontSize: 12, lineHeight: 18 },
  success: { color: '#c9e8d1', fontSize: 12, lineHeight: 18 },
  card: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 13, borderRadius: 18, backgroundColor: '#171717' },
  image: { width: 60, height: 60 },
  cardCopy: { flex: 1, gap: 6 },
  name: { color: '#fff', fontSize: 16, fontWeight: '800' },
  actions: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  actionButton: { minHeight: 35, borderRadius: 10, paddingHorizontal: 10, justifyContent: 'center', backgroundColor: '#333' },
  actionActive: { backgroundColor: '#f8df94' },
  actionText: { color: '#fff', fontSize: 11, fontWeight: '800' },
  actionActiveText: { color: '#111' },
  disabled: { opacity: 0.4 },
  empty: { padding: 18, borderRadius: 18, backgroundColor: '#171717' },
});
