import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#080808' },
  content: { paddingHorizontal: 22, paddingTop: 18, paddingBottom: 80, gap: 18 },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  iconButton: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
  title: { color: '#fff', fontSize: 32, fontWeight: '900', letterSpacing: -0.8 },
  subtitle: { color: '#9d9d9d', fontSize: 15, lineHeight: 22 },
  searchInput: { minHeight: 46, borderRadius: 16, paddingHorizontal: 13, color: '#fff', backgroundColor: '#171717' },
  summary: { flexDirection: 'row', gap: 12 },
  projectLink: { minHeight: 46, justifyContent: 'center', paddingHorizontal: 15, borderRadius: 17, backgroundColor: '#f8df94' },
  projectLinkText: { color: '#111', fontSize: 13, fontWeight: '900' },
  undoButton: { alignSelf: 'flex-start', borderRadius: 14, paddingHorizontal: 13, paddingVertical: 10, backgroundColor: '#f8df94' },
  undoText: { color: '#111', fontSize: 13, fontWeight: '800' },
  summaryCard: { flex: 1, padding: 16, borderRadius: 22, backgroundColor: '#171717' },
  summaryValue: { color: '#fff', fontSize: 26, fontWeight: '900' },
  summaryLabel: { color: '#8f8f8f', fontSize: 12, marginTop: 4 },
  toolCard: { padding: 16, borderRadius: 22, gap: 12, backgroundColor: '#131313' },
  importReview: { padding: 14, borderRadius: 16, gap: 9, backgroundColor: '#202020' },
  importReviewTitle: { color: '#fff', fontSize: 15, fontWeight: '800' },
  toolRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  button: { minHeight: 44, borderRadius: 18, paddingHorizontal: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: '#fff' },
  buttonText: { color: '#111', fontWeight: '800' },
  secondaryButton: { backgroundColor: '#252525' },
  secondaryButtonText: { color: '#fff' },
  editor: { minHeight: 150, borderRadius: 16, padding: 12, color: '#fff', backgroundColor: '#090909', textAlignVertical: 'top', fontFamily: 'monospace' },
  feedback: { color: '#c9e8d1', fontSize: 13, lineHeight: 19 },
  error: { color: '#ffb4b4' },
  card: { borderRadius: 24, padding: 16, gap: 12, backgroundColor: '#151515', borderWidth: 1, borderColor: '#242424' },
  cardTop: { flexDirection: 'row', alignItems: 'center', gap: 14 },
  image: { width: 72, height: 72 },
  cardCopy: { flex: 1 },
  name: { color: '#fff', fontSize: 19, fontWeight: '800' },
  meta: { color: '#999', fontSize: 13, marginTop: 4 },
  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: { borderRadius: 999, paddingHorizontal: 11, paddingVertical: 7, backgroundColor: '#252525' },
  chipActive: { backgroundColor: '#f8df94' },
  chipText: { color: '#d2d2d2', fontSize: 12, fontWeight: '700' },
  chipTextActive: { color: '#111' },
  deleteButton: { alignSelf: 'flex-start', paddingVertical: 7 },
  detailsButton: { alignSelf: 'flex-start', paddingVertical: 8 },
  detailsText: { color: '#f8df94', fontSize: 13, fontWeight: '800' },
  noteText: { color: '#bbb', fontSize: 12, lineHeight: 18 },
  deleteText: { color: '#ff9f9f', fontSize: 13, fontWeight: '800' },
  empty: { padding: 22, borderRadius: 24, backgroundColor: '#151515' },
  emptyText: { color: '#aaa', fontSize: 15, lineHeight: 22 },
});
