import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#050505',
  },
  content: {
    paddingHorizontal: 28,
    paddingTop: 18,
    paddingBottom: 190,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 34,
  },
  iconButton: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarCircle: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f8df94',
  },
  avatarText: {
    color: '#111111',
    fontSize: 18,
    fontWeight: '800',
  },
  greeting: {
    color: '#ffffff',
    fontSize: 42,
    fontWeight: '800',
    lineHeight: 48,
    letterSpacing: -1.4,
  },
  greetingMuted: {
    color: '#b9b9b9',
  },
  subheading: {
    color: '#7f7f7f',
    fontSize: 19,
    marginTop: 8,
    marginBottom: 28,
  },
  shortcutsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 16,
    marginBottom: 30,
  },
  sectionTitle: {
    color: '#ffffff',
    fontSize: 24,
    fontWeight: '800',
    letterSpacing: -0.6,
    marginBottom: 16,
  },
  resumeCard: {
    borderRadius: 30,
    padding: 20,
    marginBottom: 30,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  resumeTopRow: {
    flexDirection: 'row',
    gap: 16,
    alignItems: 'center',
  },
  resumeImageShell: {
    width: 108,
    height: 108,
    borderRadius: 28,
    backgroundColor: 'rgba(255,255,255,0.07)',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  resumeImage: {
    width: 94,
    height: 94,
    resizeMode: 'contain',
  },
  resumeCopy: {
    flex: 1,
    gap: 6,
  },
  resumeEmptyWrap: {
    gap: 8,
  },
  resumeEyebrow: {
    color: '#bdbdbd',
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 2.1,
  },
  resumeTitle: {
    color: '#ffffff',
    fontSize: 28,
    fontWeight: '800',
    letterSpacing: -0.9,
  },
  resumeMeta: {
    color: '#f0f0f0',
    fontSize: 15,
    fontWeight: '700',
  },
  resumeMetaMuted: {
    color: '#9a9a9a',
    fontSize: 15,
    lineHeight: 22,
  },
  resumeActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 18,
  },
  primaryAction: {
    minHeight: 52,
    borderRadius: 22,
    paddingHorizontal: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
  },
  primaryActionText: {
    color: '#111111',
    fontSize: 15,
    fontWeight: '800',
  },
  secondaryAction: {
    minHeight: 52,
    borderRadius: 22,
    paddingHorizontal: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  secondaryActionText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '800',
  },
  resumeRecentBlock: {
    marginTop: 20,
  },
  resumeRecentTitle: {
    color: '#ffffff',
    fontSize: 17,
    fontWeight: '800',
    marginBottom: 12,
  },
  collectionSection: {
    marginBottom: 30,
  },
  collectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  collectionLabel: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '800',
  },
  collectionCount: {
    color: '#a6a6a6',
    fontSize: 15,
    fontWeight: '700',
  },
  collectionSpacer: {
    height: 18,
  },
  smallCardRow: {
    paddingRight: 24,
    gap: 14,
  },
  smallCard: {
    width: 150,
    minHeight: 176,
    borderRadius: 28,
    padding: 16,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  smallCardBadge: {
    alignSelf: 'flex-start',
    minHeight: 28,
    borderRadius: 14,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  smallCardBadgeText: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  smallCardImage: {
    width: 98,
    height: 98,
    alignSelf: 'center',
    marginTop: 10,
    resizeMode: 'contain',
  },
  smallCardName: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '800',
    marginTop: 8,
  },
  smallCardMeta: {
    color: '#9d9d9d',
    fontSize: 13,
    marginTop: 3,
  },
  emptyCollectionCard: {
    borderRadius: 24,
    padding: 18,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    gap: 14,
  },
  emptyCollectionText: {
    color: '#b5b5b5',
    fontSize: 16,
    lineHeight: 24,
  },
  emptyCollectionAction: {
    alignSelf: 'flex-start',
    minHeight: 42,
    borderRadius: 21,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  emptyCollectionActionText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
  },
  backdropStripe: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: 56,
    backgroundColor: 'rgba(255,255,255,0.035)',
  },
});
