name: Expo Go Update

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: 🏗 Checkout code
        uses: actions/checkout@v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3

      - name: 🏗 Setup cache
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.lock') }}

      - name: 📦 Install dependencies
        run: npm ci --force
        shell: bash

      - name: 🏗  Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Update Expo Go
        run: eas update --auto
        shell: bash
