import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#080808' },
  content: { paddingHorizontal: 20, paddingTop: 18, paddingBottom: 90, gap: 14 },
  headerStack: { gap: 16 },
  header: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  iconButton: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
  title: { color: '#fff', fontSize: 27, fontWeight: '900', flex: 1 },
  subtitle: { color: '#aaa', fontSize: 14, lineHeight: 21 },
  card: { gap: 11, padding: 17, borderRadius: 23, backgroundColor: '#171717', borderWidth: 1, borderColor: '#2a2a2a' },
  scopePreview: { gap: 8, padding: 13, borderRadius: 15, backgroundColor: '#252525' },
  scopeWarning: { color: '#f8df94', fontSize: 12, lineHeight: 18 },
  sectionTitle: { color: '#fff', fontSize: 17, fontWeight: '900' },
  label: { color: '#eee', fontSize: 13, fontWeight: '700' },
  hint: { color: '#aaa', fontSize: 12, lineHeight: 18 },
  row: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 9 },
  flex: { flex: 1, minWidth: 110 },
  chips: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 8 },
  chip: { paddingHorizontal: 11, paddingVertical: 8, borderRadius: 99, backgroundColor: '#292929' },
  chipActive: { backgroundColor: '#f8df94' },
  chipText: { color: '#ddd', fontSize: 12, fontWeight: '800' },
  chipTextActive: { color: '#111' },
  input: { minHeight: 44, paddingHorizontal: 12, borderRadius: 14, color: '#fff', backgroundColor: '#090909' },
  primaryButton: { minHeight: 45, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 15, borderRadius: 15, backgroundColor: '#f8df94' },
  primaryText: { color: '#111', fontSize: 13, fontWeight: '900' },
  secondaryButton: { minHeight: 44, justifyContent: 'center', paddingHorizontal: 13, borderRadius: 14, backgroundColor: '#333' },
  secondaryText: { color: '#fff', fontSize: 12, fontWeight: '800' },
  disabled: { opacity: 0.4 },
  progress: { color: '#fff', fontSize: 24, fontWeight: '900' },
  progressTrack: { height: 9, borderRadius: 99, overflow: 'hidden', backgroundColor: '#353535' },
  progressFill: { height: '100%', backgroundColor: '#73d178' },
  deleteText: { color: '#ffb1b1', fontSize: 12, fontWeight: '800' },
  link: { color: '#f8df94', fontSize: 13, fontWeight: '800' },
  searchResult: { padding: 10, borderRadius: 12, backgroundColor: '#252525' },
  error: { color: '#ffb1b1', fontSize: 12 },
  targetCard: { gap: 10, padding: 14, borderRadius: 17, backgroundColor: '#151515', borderWidth: 1, borderColor: '#262626' },
  targetName: { color: '#fff', fontSize: 16, fontWeight: '800' },
  targetCount: { color: '#f8df94', fontSize: 12, fontWeight: '800', marginTop: 5 },
  empty: { padding: 20, borderRadius: 18, backgroundColor: '#171717' },
});
